#pragma once

#ifndef ENABLE_VISUALIZER
#ifdef PLATFORM_WINDOWS
#define ENABLE_VISUALIZER 1
#endif
#endif

#define USE_STABLE_SORT 1
#define USE_ROTATION_PREDICTION 1
#define USE_NAIVE_ML_DATAASSOCIATION 1

#define USE_STATIC_DETECTION 1

#define STATIC_OBSERVER 1

#define USE_HARRIS 0

#define TEST_VISION_MODULE 0
